[package]
name = "poprustica"
version = "0.1.0"
edition = "2024"

[dependencies]
winit = "0.30.9"
wgpu = "24.0.3"
pollster = "0.3"
bytemuck = { version = "1.16", features = [ "derive" ] }
anyhow = "1.0"

[dependencies.image]
version = "0.24"
default-features = false
features = ["png", "jpeg"]